server:
 port: 9000
spring:
  cloud:
    gateway:
      routes:
      - id: api
        uri: https://api.mercadolibre.com
        predicates:
         - Path=/meli/**
        filters:
         - RewritePath=/meli,/